# Generated by Django 4.2.7 on 2025-11-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("USER", "user"), ("ADMIN", "admin")],
                default="USER",
                max_length=20,
            ),
        ),
    ]
