# Generated by Django 4.2.7 on 2025-11-20 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("media_library", "0001_initial"),
        ("api", "0002_add_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="default_media_folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_users",
                to="media_library.mediafolder",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preferences",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
