# Generated by Django 4.2.7 on 2025-11-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("affiliates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliatelink",
            name="link_type",
            field=models.CharField(
                choices=[("static", "Static"), ("dynamic", "Dynamic")],
                default="static",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="affiliatelink",
            name="url",
            field=models.URLField(help_text="The actual affiliate URL or template"),
        ),
    ]
