# Generated by Django 4.2.7 on 2025-11-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="available_variables",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of variables found in the template",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="fingerprint_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Template-specific fingerprinting rules",
            ),
        ),
    ]
