# Generated by Django 4.2.7 on 2025-11-21 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "__first__"),
        ("api", "0003_user_default_media_folder_user_preferences"),
        ("media_library", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mediafolder",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="mediaasset",
            name="alt_text",
        ),
        migrations.RemoveField(
            model_name="mediaasset",
            name="title",
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="fingerprint_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="format",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="mediafolder",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_folders",
                to="sites.site",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mediafolder",
            unique_together={("name", "parent", "owner", "site")},
        ),
        migrations.CreateModel(
            name="MediaAssetSiteData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "custom_filename",
                    models.CharField(
                        blank=True,
                        help_text="Site-specific filename override",
                        max_length=255,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_data",
                        to="media_library.mediaasset",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_assets_data",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "unique_together": {("asset", "site")},
            },
        ),
    ]
