# Generated by Django 4.2.7 on 2025-11-23 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("media_library", "0002_alter_mediafolder_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediaasset",
            name="alt_text",
        ),
        migrations.RemoveField(
            model_name="mediaasset",
            name="title",
        ),
    ]
