# Generated by Django 4.2.7 on 2025-11-23 15:20

from django.db import migrations, models
import django.db.models.deletion
# import removed - django_cryptography not used


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sites", "0005_swiperpreset_created_by_alter_swiperpreset_site"),
    ]

    operations = [
        migrations.CreateModel(
            name="UmamiConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_url", models.URLField(help_text="Umami API endpoint URL")),
                (
                    "api_token",
                    models.CharField(
                        help_text="Encrypted API token",
                        max_length=255,
                    ),
                ),
                (
                    "umami_site_id",
                    models.CharField(help_text="Site ID in Umami", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="umami_config",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Umami Configuration",
                "verbose_name_plural": "Umami Configurations",
            },
        ),
        migrations.CreateModel(
            name="AnalyticsCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Date for this analytics data")),
                ("page_views", models.IntegerField(default=0)),
                ("unique_visitors", models.IntegerField(default=0)),
                (
                    "bounce_rate",
                    models.FloatField(default=0.0, help_text="Bounce rate percentage"),
                ),
                (
                    "avg_session_duration",
                    models.IntegerField(
                        default=0, help_text="Average session duration in seconds"
                    ),
                ),
                (
                    "top_pages",
                    models.JSONField(
                        blank=True, default=list, help_text="Top pages with view counts"
                    ),
                ),
                (
                    "traffic_sources",
                    models.JSONField(
                        blank=True, default=list, help_text="Traffic source breakdown"
                    ),
                ),
                (
                    "device_breakdown",
                    models.JSONField(
                        blank=True, default=dict, help_text="Device/browser statistics"
                    ),
                ),
                (
                    "geographic_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Geographic distribution"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_cache",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics Cache",
                "verbose_name_plural": "Analytics Caches",
                "ordering": ["-date"],
                "unique_together": {("site", "date")},
            },
        ),
    ]
