# Generated by Django 4.2.7 on 2025-11-20 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api", "0003_user_default_media_folder_user_preferences"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable identifier", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description"),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("title", "Title"),
                            ("description", "Description"),
                            ("h1", "H1 Heading"),
                            ("faq", "FAQ"),
                            ("hero", "Hero Section"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "ai_model",
                    models.CharField(
                        choices=[
                            ("gpt-4", "GPT-4"),
                            ("gpt-3.5-turbo", "GPT-3.5 Turbo"),
                            ("grok-beta", "Grok Beta"),
                            ("claude-3-opus", "Claude 3 Opus"),
                        ],
                        default="gpt-4",
                        max_length=50,
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.7, help_text="Creativity control (0.0 to 1.0)"
                    ),
                ),
                (
                    "template",
                    models.TextField(
                        help_text="Prompt text with {{variable}} placeholders"
                    ),
                ),
                (
                    "input_variables",
                    models.JSONField(
                        default=list,
                        help_text="List of expected variables e.g. ['keywords', 'brand']",
                    ),
                ),
                (
                    "output_format",
                    models.CharField(
                        choices=[
                            ("html", "HTML"),
                            ("markdown", "Markdown"),
                            ("text", "Plain Text"),
                        ],
                        default="html",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="text_prompts",
                        to="api.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImagePrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "DALL-E (OpenAI)"),
                            ("midjourney", "Midjourney"),
                            ("stability", "Stability AI"),
                        ],
                        default="openai",
                        max_length=50,
                    ),
                ),
                ("template", models.TextField(help_text="Image generation prompt")),
                (
                    "style_preset",
                    models.CharField(
                        choices=[
                            ("realistic", "Realistic"),
                            ("illustrated", "Illustrated"),
                            ("minimalist", "Minimalist"),
                            ("cyberpunk", "Cyberpunk"),
                            ("studio", "Studio Photo"),
                        ],
                        default="realistic",
                        max_length=50,
                    ),
                ),
                ("width", models.IntegerField(default=1024)),
                ("height", models.IntegerField(default=1024)),
                (
                    "format",
                    models.CharField(
                        choices=[("png", "PNG"), ("jpg", "JPG"), ("webp", "WebP")],
                        default="png",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="image_prompts",
                        to="api.user",
                    ),
                ),
            ],
        ),
    ]
