# Generated by Django 4.2.7 on 2025-11-20 12:26

from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api", "0003_user_default_media_folder_user_preferences"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Human-readable identifier for the token (e.g., "Production OpenAI", "OpenRouter Multi-Model")',
                        max_length=200,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI / ChatGPT"),
                            ("grok", "Grok"),
                            ("cloudflare", "Cloudflare Pages"),
                            ("openrouter", "OpenRouter"),
                        ],
                        help_text="Which service this token is for",
                        max_length=50,
                    ),
                ),
                (
                    "token_value",
                    fernet_fields.fields.EncryptedCharField(
                        help_text="The actual API token (encrypted in database)",
                        max_length=500,
                    ),
                ),
                (
                    "ai_model",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gpt-4", "GPT-4"),
                            ("gpt-4-turbo", "GPT-4 Turbo"),
                            ("gpt-3.5-turbo", "GPT-3.5 Turbo"),
                            ("grok-beta", "Grok Beta"),
                            ("openai/gpt-4", "OpenRouter: GPT-4"),
                            ("openai/gpt-4-turbo", "OpenRouter: GPT-4 Turbo"),
                            ("openai/gpt-3.5-turbo", "OpenRouter: GPT-3.5 Turbo"),
                            (
                                "anthropic/claude-3.5-sonnet",
                                "OpenRouter: Claude 3.5 Sonnet",
                            ),
                            ("anthropic/claude-3-opus", "OpenRouter: Claude 3 Opus"),
                            ("anthropic/claude-3-haiku", "OpenRouter: Claude 3 Haiku"),
                            (
                                "google/gemini-2.0-flash-exp",
                                "OpenRouter: Gemini 2.0 Flash",
                            ),
                            ("google/gemini-pro-1.5", "OpenRouter: Gemini Pro 1.5"),
                            (
                                "meta-llama/llama-3.1-70b-instruct",
                                "OpenRouter: Llama 3.1 70B",
                            ),
                            ("mistralai/mistral-large", "OpenRouter: Mistral Large"),
                            ("x-ai/grok-2", "OpenRouter: Grok 2"),
                            ("deepseek/deepseek-chat", "OpenRouter: DeepSeek Chat"),
                            ("qwen/qwen-2.5-72b-instruct", "OpenRouter: Qwen 2.5 72B"),
                        ],
                        help_text="AI model to use (only for OpenAI/Grok/OpenRouter tokens)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this token is available for use",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this token was last used for an API call",
                        null=True,
                    ),
                ),
                (
                    "current_usage",
                    models.IntegerField(
                        default=0, help_text="Total usage count for this token"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Admin user who created this token",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tokens",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Token",
                "verbose_name_plural": "API Tokens",
                "ordering": ["service_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["service_type", "is_active"],
                        name="apitoken_service_active_idx",
                    ),
                    models.Index(fields=["service_type"], name="apitoken_service_idx"),
                    models.Index(fields=["is_active"], name="apitoken_active_idx"),
                ],
            },
        ),
    ]
