# Generated by Django 4.2.7 on 2025-11-23 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tokens", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitoken",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who owns this token",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="apitoken",
            name="ai_model",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gpt-4", "GPT-4"),
                    ("gpt-4-turbo", "GPT-4 Turbo"),
                    ("gpt-3.5-turbo", "GPT-3.5 Turbo"),
                    ("grok-beta", "Grok Beta"),
                    ("gemini-pro", "Gemini Pro"),
                    ("gemini-ultra", "Gemini Ultra"),
                    ("openrouter/auto", "OpenRouter Auto"),
                ],
                help_text="AI model to use (only for OpenAI/Grok/OpenRouter tokens)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="apitoken",
            name="name",
            field=models.CharField(
                help_text='Friendly name for this token (e.g., "My OpenAI Key")',
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="apitoken",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI / ChatGPT"),
                    ("grok", "Grok"),
                    ("cloudflare", "Cloudflare Pages"),
                    ("openrouter", "OpenRouter"),
                    ("google", "Google AI"),
                ],
                help_text="Which service this token is for",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="apitoken",
            name="token_value",
            field=models.CharField(
                help_text="The actual API token (store encrypted in production)",
                max_length=500,
            ),
        ),
    ]
