# Generated by Django 4.2.7 on 2025-11-21 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("templates", "0002_template_available_variables_and_more"),
        ("affiliates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("domain", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("language", models.CharField(default="en-US", max_length=10)),
                ("brand_name", models.CharField(blank=True, max_length=255)),
                ("logo_url", models.URLField(blank=True)),
                ("favicon_url", models.URLField(blank=True)),
                (
                    "geo_targeting",
                    models.CharField(
                        blank=True,
                        help_text="Optional region for optimization",
                        max_length=100,
                    ),
                ),
                (
                    "fingerprint_type",
                    models.CharField(
                        choices=[
                            ("random_class", "Random Class Names"),
                            ("preset_scheme", "Preset Naming Scheme"),
                            ("wordpress", "WordPress Footprint"),
                            ("other_cms", "Other CMS Footprint"),
                        ],
                        default="random_class",
                        max_length=50,
                    ),
                ),
                (
                    "allow_indexing",
                    models.BooleanField(
                        default=True, help_text="If false, adds noindex meta tag"
                    ),
                ),
                ("redirect_404_to_homepage", models.BooleanField(default=False)),
                ("force_www", models.BooleanField(default=False)),
                (
                    "page_speed_optimization",
                    models.BooleanField(
                        default=False,
                        help_text="Enable image optimization and lazy loading",
                    ),
                ),
                ("microdata_settings", models.JSONField(blank=True, default=dict)),
                ("header_cta_config", models.JSONField(blank=True, default=dict)),
                ("footer_images", models.JSONField(blank=True, default=list)),
                (
                    "custom_head_html",
                    models.TextField(
                        blank=True, help_text="Custom HTML for <head> section"
                    ),
                ),
                (
                    "affiliate_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="affiliates.affiliatelink",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="templates.template",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, help_text="Max 60 chars recommended", max_length=60
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Max 160 chars recommended",
                        max_length=160,
                    ),
                ),
                ("h1_heading", models.CharField(blank=True, max_length=255)),
                (
                    "use_h1_in_hero",
                    models.BooleanField(
                        default=False, help_text="If checked, H1 renders in hero block"
                    ),
                ),
                ("canonical_url", models.URLField(blank=True)),
                (
                    "custom_head_html",
                    models.TextField(
                        blank=True, help_text="Custom HTML for <head> section"
                    ),
                ),
                (
                    "primary_keywords",
                    models.TextField(blank=True, help_text="One keyword per line"),
                ),
                (
                    "lsi_keywords",
                    models.TextField(
                        blank=True,
                        help_text="Latent Semantic Index keywords, one per line",
                    ),
                ),
                ("published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "unique_together": {("site", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("commit_hash", models.CharField(blank=True, max_length=100)),
                ("log", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployments",
                        to="sites.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero Section"),
                            ("article", "Article"),
                            ("image", "Image"),
                            ("cta", "Call to Action"),
                            ("faq", "FAQ"),
                            ("swiper", "Swiper/Slider"),
                            ("custom", "Custom HTML"),
                        ],
                        max_length=50,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("content", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="sites.page",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
