# Generated by Django 4.2.7 on 2025-11-21 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="type",
            field=models.CharField(
                choices=[
                    ("hero", "Hero Section"),
                    ("article", "Article"),
                    ("image", "Image"),
                    ("text_image", "Text + Image"),
                    ("cta", "Call to Action"),
                    ("faq", "FAQ"),
                    ("swiper", "Swiper/Slider"),
                    ("custom", "Custom HTML"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="SwiperPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "items",
                    models.JSONField(
                        default=list, help_text="List of items with image, title, etc."
                    ),
                ),
                ("button_text", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swiper_presets",
                        to="sites.site",
                    ),
                ),
            ],
        ),
    ]
