# Generated by Django 4.2.7 on 2025-11-22 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0002_alter_block_type_swiperpreset"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="block",
            options={},
        ),
        migrations.AddField(
            model_name="block",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="block",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
