# Generated by Django 4.2.7 on 2025-11-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0003_alter_block_options_block_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="custom_body_html",
            field=models.TextField(
                blank=True, help_text="Custom HTML for end of <body> section"
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="custom_css",
            field=models.TextField(blank=True, help_text="Custom CSS"),
        ),
        migrations.AddField(
            model_name="site",
            name="custom_js",
            field=models.TextField(blank=True, help_text="Custom JavaScript"),
        ),
        migrations.AddField(
            model_name="site",
            name="template_config",
            field=models.JSONField(
                blank=True, default=dict, help_text="Values for template variables"
            ),
        ),
    ]
