# Generated by Django 4.2.7 on 2025-11-23 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sites", "0004_site_custom_body_html_site_custom_css_site_custom_js_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="swiperpreset",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="swiper_presets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="swiperpreset",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="swiper_presets",
                to="sites.site",
            ),
        ),
    ]
