# Generated by Django 4.2.7 on 2025-11-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LanguagePreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("ordering", models.IntegerField(default=0, help_text="Display order")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Language Preset",
                "verbose_name_plural": "Language Presets",
                "ordering": ["ordering", "name"],
                "indexes": [models.Index(fields=["code"], name="language_code_idx")],
            },
        ),
    ]
